version: '3.7'

volumes:
  pg_data: {}

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: sheds_db
      POSTGRES_USER: sheds_user
      POSTGRES_PASSWORD: sheds_password
    ports:
      - "55999:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  celery:
    build:
      context: ./backend
    command: celery -A config worker -l info --concurrency=2
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/app
    restart: always
