# Generated by Django 6.0 on 2026-06-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', max_length=2)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modificado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('ticket_status_changed', 'Status do Ticket Alterado'),
                            ('ticket_assigned', 'Ticket Atribuído'),
                            ('ticket_unassigned', 'Ticket Desatribuído'),
                        ],
                        default='ticket_status_changed',
                        max_length=50,
                    ),
                ),
                ('content', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificação do Usuário',
                'verbose_name_plural': 'Notificações dos Usuários',
            },
        ),
    ]
