# Generated by Django 6.0 on 2026-06-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modificado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', max_length=2)),
                (
                    'type',
                    models.CharField(
                        choices=[('admin', 'Administrador'), ('technician', 'Técnico'), ('customer', 'Cliente')], default='customer', max_length=20
                    ),
                ),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'permissions': [('change_permissions', 'Can change user permissions')],
            },
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modificado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('ticket_status_changed', 'Status do Ticket Alterado'),
                            ('ticket_assigned', 'Ticket Atribuído'),
                            ('ticket_unassigned', 'Ticket Desatribuído'),
                        ],
                        default='ticket_status_changed',
                        max_length=50,
                    ),
                ),
                ('content', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificação do Usuário',
                'verbose_name_plural': 'Notificações dos Usuários',
            },
        ),
    ]
