# Generated by Django 6.0 on 2026-06-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('technician', 'Técnico'), ('customer', 'Cliente')], default='customer', max_length=20),
        ),
    ]
