# Generated by Django 6.0 on 2026-06-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usernotifications_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='kind',
            field=models.CharField(
                choices=[
                    ('ticket_status_changed', 'Status do Ticket Alterado'),
                    ('ticket_assigned', 'Ticket Atribuído'),
                    ('ticket_unassigned', 'Ticket Desatribuído'),
                    ('ticket_commented', 'Novo Comentário no Ticket'),
                ],
                default='ticket_status_changed',
                max_length=50,
            ),
        ),
    ]
