LIGHT_THEME_OPTION = 'light'
DARK_THEME_OPTION = 'dark'

THEME_CHOICES = [(LIGHT_THEME_OPTION, 'Light'), (DARK_THEME_OPTION, 'Dark')]

POSSIBLE_THEMES = [LIGHT_THEME_OPTION, DARK_THEME_OPTION]

EN_LANGUAGE_OPTION = "en"
PT_LANGUAGE_OPTION = "pt"

LANGUAGE_CHOICES = [(EN_LANGUAGE_OPTION, "English"), (PT_LANGUAGE_OPTION, "Português")]

POSSIBLE_LANGUAGES = [EN_LANGUAGE_OPTION, PT_LANGUAGE_OPTION]

STEP1_OPTION = 'step1'
STEP2_OPTION = 'step2'
STEP3_OPTION = 'step3'
FINAL_STEP_OPTION = 'final_step'

STEP_CHOICES = [
    (STEP1_OPTION, 'Step 1'),
    (STEP2_OPTION, 'Step 2'),
    (STEP3_OPTION, 'Step 3'),
    (FINAL_STEP_OPTION, 'Final Step'),
]

POSSIBLE_STEPS = [STEP1_OPTION, STEP2_OPTION, STEP3_OPTION, FINAL_STEP_OPTION]
