# Generated by Django 6.0 on 2026-06-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticketattachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='historicalticketattachment',
            name='file_url',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='file_url',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
