# Generated by Django 6.0 on 2026-06-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255, unique=True)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', max_length=2)),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('allow_customer_signup', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='app_logos/')),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('notify_on_comment', models.BooleanField(default=True)),
                ('notify_on_status_change', models.BooleanField(default=True)),
                ('notify_on_assignment', models.BooleanField(default=True)),
                ('auto_close_inactive_tickets', models.BooleanField(default=False)),
                ('auto_close_after_days', models.PositiveIntegerField(default=30)),
                (
                    'default_ticket_priority',
                    models.CharField(choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], default='medium', max_length=20),
                ),
                ('log_retention_days', models.PositiveIntegerField(default=90)),
                ('oci_tenancy_ocid', models.CharField(blank=True, max_length=255, null=True)),
                ('oci_user_ocid', models.CharField(blank=True, max_length=255, null=True)),
                ('oci_key_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('oci_private_key', models.CharField(blank=True, max_length=255, null=True)),
                ('oci_region', models.CharField(blank=True, max_length=255, null=True)),
                ('oci_compartment_ocid', models.CharField(blank=True, max_length=255, null=True)),
                ('oci_bucket_name', models.CharField(blank=True, max_length=255, null=True)),
                ('oci_bucket_namespace', models.CharField(blank=True, max_length=255, null=True)),
                ('oci_sender_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
