# Generated by Django 6.0 on 2026-06-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='step',
            field=models.CharField(
                choices=[('step1', 'Step 1'), ('step2', 'Step 2'), ('step3', 'Step 3'), ('final_step', 'Final Step')], default='step1', max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='notify_on_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='notify_on_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='notify_on_status_change',
            field=models.BooleanField(default=False),
        ),
    ]
