EN_LANGUAGE_OPTION = "en"
PT_LANGUAGE_OPTION = "pt"

LANGUAGE_CHOICES = [
    (EN_LANGUAGE_OPTION, "English"),
    (PT_LANGUAGE_OPTION, "Português")
]

NOTIFICATION_KIND_TICKET_STATUS_CHANGED = 'ticket_status_changed'
NOTIFICATION_KIND_TICKET_ASSIGNED = 'ticket_assigned'
NOTIFICATION_KIND_TICKET_UNASSIGNED = 'ticket_unassigned'
NOTIFICATION_KIND_CHOICES = [
    (NOTIFICATION_KIND_TICKET_STATUS_CHANGED, 'Status do Ticket Alterado'),
    (NOTIFICATION_KIND_TICKET_ASSIGNED, 'Ticket Atribuído'),
    (NOTIFICATION_KIND_TICKET_UNASSIGNED, 'Ticket Desatribuído')
]

ADMIN_USER_TYPE = 'admin'
TECHNICIAN_USER_TYPE = 'technician'
CUSTOMER_USER_TYPE = 'customer'

USER_TYPE_CHOICES = [
    (ADMIN_USER_TYPE, 'Administrador'),
    (TECHNICIAN_USER_TYPE, 'Técnico'),
    (CUSTOMER_USER_TYPE, 'Cliente')
]